module.exports = {
  CHANGE_SORT: 'CHANGE_SORT',
  LOAD_SETS: 'LOAD_SETS',
  SHUFFLE_CARDS: 'SHUFFLE_CARDS',
  START_QUIZ: 'START_QUIZ',
  QUIZ_CARD_CORRECT: 'QUIZ_CARD_CORRECT',
  QUIZ_CARD_INCORRECT: 'QUIZ_CARD_INCORRECT',
<<<<<<< HEAD
  QUIZ_CARD_SKIP: 'QUIZ_CARD_SKIP'
=======
  TOGGLE_CARD: 'TOGGLE_CARD'
>>>>>>> f866f915080cb96578d34ba318f246a46b06d3d7
}
